### ISSUE TITLE
backgroundColor parameter for buttonColors should be removed

### ISSUE THREAD

**Issue by soleil-colza** [dev-xero/art-space#3]
My environment is:

M1 Macbook Air
macOS 14.2.1
Android Studio Hedgehog 2023.1.1 Patch 1

In the MainActivity.kt line 101-103, the backgroundColor parameter is given like:

`colors = ButtonDefaults.buttonColors(
					backgroundColor = colorResource(id = R.color.gray_900)
				),`

However, the backgroundColor parameter cannot be found, so it should be written like:

`colors = ButtonDefaults.buttonColors(colorResource(id = R.color.gray_900)),`

My deep apologies if it was my local or version issue. I appreciate any feedback.

**Comment by dev-xero** [comment]
I appreciate the feedback. This was just a little project from when I started learning Android Development. It's likely some compose syntax has changed.

Thanks again.
